# Generated by Django 3.1.7 on 2022-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=30)),
                ('video', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('results', models.CharField(max_length=10000)),
            ],
        ),
    ]
